version: '3.8'

secrets:
  DB_ROOT_PWD:
    file: .secrets/db_root_pwd.txt
  MYSQL_PWD:
    file: .secrets/mysql_pwd.txt

services:
  app:
    image: 'jc21/nginx-proxy-manager:github-s6-verbose'
    restart: unless-stopped
    network_mode: 'host'
    # ports:
    #   - '80:80'
    #   - '81:81'
    #   - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    environment:
      DB_MYSQL_HOST: 'host.docker.internal'
      DB_MYSQL_PORT: '3306'
      DB_MYSQL_USER: 'npm'
      DB_MYSQL_PASSWORD__FILE: /run/secrets/MYSQL_PWD
      DB_MYSQL_NAME: 'npm'
      DISABLE_IPV6: 'false'
    healthcheck:
      test: [ "CMD", "/bin/check-health" ]
      interval: 10s
      timeout: 3s
    secrets:
      - MYSQL_PWD
    depends_on:
      - db
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db:
    image: mariadb:latest
    restart: unless-stopped
    # network_mode: 'host'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/DB_ROOT_PWD
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD_FILE: /run/secrets/MYSQL_PWD
    command: --bind-address=0.0.0.0 --default-storage-engine=aria
    volumes:
      - mariadb_data:/var/lib/mysql
    secrets:
      - DB_ROOT_PWD
      - MYSQL_PWD
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 10s
      timeout: 3s

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30
    environment:
      WATCHTOWER_NOTIFICATION_URL: 'pushover://shoutrrr:a7vzxg4vg5a8tprj8ifxi9kwxy2rzq@uLCnNuNPeE9t7KTvVbFv6fPejYw5WX'
      
volumes:
  mariadb_data: